// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpgGsoaHuPe5bmGNBHxyUsOf3-z3j9mSM',
    appId: '1:610930278518:web:62407cb9969be5e4b71f57',
    messagingSenderId: '610930278518',
    projectId: 'news-app-5a70d',
    authDomain: 'news-app-5a70d.firebaseapp.com',
    storageBucket: 'news-app-5a70d.firebasestorage.app',
    measurementId: 'G-M79TF38Y1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxrgh_w4S5famk3179EnH1pRKqUtd73yA',
    appId: '1:610930278518:android:4253ffa1e09001e8b71f57',
    messagingSenderId: '610930278518',
    projectId: 'news-app-5a70d',
    storageBucket: 'news-app-5a70d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByPzNkWon0Ah6HFGABv7JysAgsAgAISoU',
    appId: '1:610930278518:ios:6c6e819009b01b52b71f57',
    messagingSenderId: '610930278518',
    projectId: 'news-app-5a70d',
    storageBucket: 'news-app-5a70d.firebasestorage.app',
    iosBundleId: 'com.example.cnn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByPzNkWon0Ah6HFGABv7JysAgsAgAISoU',
    appId: '1:610930278518:ios:6c6e819009b01b52b71f57',
    messagingSenderId: '610930278518',
    projectId: 'news-app-5a70d',
    storageBucket: 'news-app-5a70d.firebasestorage.app',
    iosBundleId: 'com.example.cnn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpgGsoaHuPe5bmGNBHxyUsOf3-z3j9mSM',
    appId: '1:610930278518:web:99e1951e18820031b71f57',
    messagingSenderId: '610930278518',
    projectId: 'news-app-5a70d',
    authDomain: 'news-app-5a70d.firebaseapp.com',
    storageBucket: 'news-app-5a70d.firebasestorage.app',
    measurementId: 'G-2SC8T6MFRX',
  );
}
